---
# Source: postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-postgresql-sealed
  namespace: "hornet"
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-12.5.8
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/family: dnext
  annotations:
    pia-team.com/app: postgres
    pia-team.com/app-logo: postgres
    pia-team.com/app-title: Postgres
    pia-team.com/role: pia.k8s.postgres/0.5.1
    pia-team.com/secret-status: sealed
    pia-team.com/iv: eio7P6Rmbp+u8GhddIlCGg==
    pia-team.com/session-key: 
      XFKbEYNuFPv+x5B6JeVlOt7Dz86RqnS30TbEDrS3Z66jPLCii+LuooqgZlUek4Y6TRB/Gk6/FsGG1zo6Hy/b1jgS0Qmsyr6Fu17tQDjctK+iyDrk7w7CE7bsQIRoegc/JyW8gHA8d2RjymXCWne2pDSpNIUp0o942LOZ6qBX7MOzAMLFeEXwLC/a9db+jx9lsVzkCDHuHMV9IMUgIIYiu9wxRlnhahRKMFLkiWFcxlPQ+qE4cd13CR8pE6Kc2Mh73JRyEVhKVRrQ1w3HWIKaM7wCaopB/HDkZDKJ6BnyWs5TjhFA3Bfo1xuTs0ylUOF+MCiHBGSFUzjlzig57iSsYg==
type: Opaque
data:
  postgres-password: "CQjhjivY3TIe+uumZnXgibz1iW0="
  password: "CQjhjivY3TIe+uumZnXgibz1iW0="
  # We don't auto-generate LDAP password when it's not provided as we do for other passwords
