---
# Source: mongodb/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-sealed
  namespace: hornet
  labels:
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-11.0.6-1
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/family: dnext
  annotations:
    pia-team.com/app: mongodb
    pia-team.com/app-logo: mongodb
    pia-team.com/app-title: MongoDB
    pia-team.com/role: pia.k8s.mongodb/0.5.3
    pia-team.com/secret-status: sealed
    pia-team.com/iv: HZlQmQlkfcvtTq9UZReFug==
    pia-team.com/session-key: 
      oLgMpi9NJcWKXh1/iri59QvwA06OTCjFCyqowUoxzJvw4DBJSgVPDwaTmPeXBw7iKHVCHpNGIs8d2rZXPT7/PPVntnjfKOGCPOmSO6C+Ds6AEL08PU4zz/vBEIOx7LpdpAfl2H/X16f+NFAXWNtzfdXq5mrgW7Y4jmhqReaiIOHtgegjsy0y5LxGslcp66QoVUuPm0b3QTuILIuLOCrihghNsf9f85i1Da0j9TdyEKTpsZCKY5EoAAD0yNsXsuemaMMUdGHFABDYj6Bki6NkRc6EPrBweZo35OJxU98IqVfL9EM3l686gdKm8Q3qQyMfmuVSOesLd/r+HxXYNyPqfQ==
type: Opaque
data:
  mongodb-root-password: "x3C5UJ8GGbb31BdU3E9eDYSTsiM="
  mongodb-replica-set-key: "x3C5UJ8GGbb31BdU3E9eDYSTsiM="
