---
# Source: mongodb/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb
  namespace: hornet
  labels:
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-11.0.6-1
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/managed-by: Helm
  annotations:
    pia-team.com/app: mongodb
    pia-team.com/app-logo: mongodb
    pia-team.com/app-title: MongoDB
    pia-team.com/role: pia.k8s.mongodb/0.5.3
secrets:
- name: mongodb
