---
# Source: camunda-bpm-platform/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: camunda-camunda-bpm-platform
  labels:
    helm.sh/chart: camunda-bpm-platform-7.6.4
    app.kubernetes.io/name: camunda-bpm-platform
    app.kubernetes.io/instance: camunda
    app.kubernetes.io/version: "7.x.x"
    app.kubernetes.io/managed-by: Helm
  annotations:
    pia-team.com/role: pia.k8s.camunda/0.7.0
