---
# Source: elasticsearch/templates/poddisruptionbudget.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: "elasticsearch-master-pdb"
  annotations:
    pia-team.com/role: pia.k8s.elastic/0.5.0
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: "elasticsearch-master"
