---
# Source: app/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: account-ui-sealed
  labels:
    app.kubernetes.io/name: account-ui
    app.kubernetes.io/family: dnext
    helm.sh/chart: app-0.9.1
    app.kubernetes.io/instance: account-ui
    app.kubernetes.io/managed-by: Helm
  annotations:
    pia-team.com/role: pia.k8s.apps/0.35.0/orbitant/account-ui
    pia-team.com/secret-status: sealed
    pia-team.com/iv: UX1mkEi8IqzZ0y2V58/XUQ==
    pia-team.com/session-key: 
      2JYF+SVytXMV/nXEC1/jxoQ9Nk/lMNKkL0+25Y2J54WucBRX6TjQ/55YFDpkHSm305GmdEfoSU5s513fmsqnaEY5pypR+bfv+qVM0b8hhI9nVuGwdQGKxjake9REFE3AZX8KFYei7whc4AJksPV58RNs26G3TWLSzhcrcnP4oWUCHFhR3zHl66h+aR4Vg+ptS+i3pEwFqSBccNy/bfmv5LxiL/i+D0XMVzD66UDukD2anz5XB7EQkgVhxk4qup3kQAMF9mng4WVqs5Va0crMpCuByHSQOtfNCGsPHL0zZKEZbq4v3ocAJd9eeNshwXILZ0TBf9+E0M15VeOAW7fm7A==
type: Opaque
data:
