---
# Source: jaeger/charts/kafka/templates/rbac/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jaeger-kafka
  namespace: "hornet"
  labels:
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka
    app.kubernetes.io/version: 3.6.1
    helm.sh/chart: kafka-26.6.2
    app.kubernetes.io/component: kafka
  annotations:
    pia-team.com/role: pia.k8s.jaeger/0.5.0
automountServiceAccountToken: true
