---
apiVersion: v1
kind: Secret
metadata:
  name: voltran-repo
  namespace: "argocd"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/gokhansengun/minikube-argocd-ext
  password: fill-this-in
  username: fill-this-in
