---
# Source: minio/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio
  namespace: "hornet"
  labels:
    app.kubernetes.io/name: minio
    helm.sh/chart: minio-11.10.3
    app.kubernetes.io/instance: minio
    app.kubernetes.io/managed-by: Helm
  annotations:
    pia-team.com/app: minio
    pia-team.com/app-logo: minio
    pia-team.com/app-title: MinIO
    pia-team.com/role: pia.k8s.minio/0.6.0
automountServiceAccountToken: true
secrets:
- name: minio
