---
# Source: logstash/templates/dnext-logstash-config.yml
apiVersion: v1
data:
  role: pia.k8s.elastic/0.5.0
kind: ConfigMap
metadata:
  name: dnext-logstash-config
  annotations:
    pia-team.com/role: pia.k8s.elastic/0.5.0
