---
# Source: logstash/templates/service.yaml
kind: Service
apiVersion: v1
metadata:
  name: "logstash-logstash"
  labels:
    app: "logstash-logstash"
    chart: "logstash"
    heritage: "Helm"
    release: "logstash"
  annotations:
    pia-team.com/app: logstash
    pia-team.com/app-logo: logstash
    pia-team.com/app-title: Logstash
    pia-team.com/role: pia.k8s.elastic/0.5.0
spec:
  type: ClusterIP
  selector:
    app: "logstash-logstash"
    chart: "logstash"
    release: "logstash"
  ports:
  - name: beats
    port: 5044
    protocol: TCP
    targetPort: 5044
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
