---
# Source: logstash/templates/service-headless.yaml
kind: Service
apiVersion: v1
metadata:
  name: "logstash-logstash-headless"
  labels:
    app: "logstash-logstash"
    chart: "logstash"
    heritage: "Helm"
    release: "logstash"
  annotations:
    pia-team.com/role: pia.k8s.elastic/0.5.0
spec:
  clusterIP: None
  selector:
    app: "logstash-logstash"
  ports:
  - name: http
    port: 9600
