---
# Source: kafka/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka
  namespace: "hornet"
  labels:
    app.kubernetes.io/name: kafka
    helm.sh/chart: kafka-18.4.2
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: kafka
  annotations:
    pia-team.com/app: kafka
    pia-team.com/app-logo: kafka
    pia-team.com/app-title: Kafka
    pia-team.com/role: pia.k8s.kafka/0.4.1
automountServiceAccountToken: true
