---
# Source: redis-ha/templates/redis-ha-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-ha
  namespace: "hornet"
  labels:
    heritage: Helm
    release: redis-ha
    chart: redis-ha-4.23.0
    app: redis-ha
  annotations:
    pia-team.com/role: pia.k8s.redis-ha/0.4.1
imagePullSecrets:
- name: reg-creds
