---
# Source: xxxxx/templates/jenkins-in-cluster-auth.yml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins-deployer
  annotations:
    pia-team.com/role: pia.k8s.jenkins.customer/0.12.0
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: hornet
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hornet
