---
# Source: jenkins/templates/jenkins-controller-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jenkins
  namespace: hornet
  labels:
    "app.kubernetes.io/name": 'jenkins'
    "helm.sh/chart": "jenkins-3.8.8"
    "app.kubernetes.io/managed-by": "Helm"
    "app.kubernetes.io/instance": "jenkins"
    "app.kubernetes.io/component": "jenkins-controller"
  annotations:
    pia-team.com/role: pia.k8s.jenkins.customer/0.12.0
spec:
  serviceName: jenkins
  replicas: 1
  selector:
    matchLabels:
      "app.kubernetes.io/component": "jenkins-controller"
      "app.kubernetes.io/instance": "jenkins"
  template:
    metadata:
      labels:
        "app.kubernetes.io/name": 'jenkins'
        "app.kubernetes.io/managed-by": "Helm"
        "app.kubernetes.io/instance": "jenkins"
        "app.kubernetes.io/component": "jenkins-controller"
      annotations:
        checksum/config: 761ba61001154d002ad29377f4bb3020551252d9f7fb6f2f0d271f54f391a4d8
    spec:
      securityContext:
        fsGroup: 0
        runAsNonRoot: false
        runAsUser: 1000
      serviceAccountName: "jenkins"
      initContainers:
      - name: "init"
        image: "europe-docker.pkg.dev/dnext-io/ghcr-dnext-technology/dnext-technology/fletcher:v0.12.0"
        imagePullPolicy: "IfNotPresent"
        command: ["sh", "/var/jenkins_config/apply_config.sh"]
        env:
        - name: JENKINS_UC
          value: http://git-http/static/jenkins-plugins-stable
        resources:
          limits:
            cpu: 2000m
            memory: 2048Mi
          requests:
            cpu: 250m
            memory: 1536Mi
        volumeMounts:
        - mountPath: /tmp/pia/groovy
          name: jenkins-groovy-folder
          readOnly: true
        - mountPath: /tmp/pia/groovy-render
          name: jenkins-groovy-render-folder
        - mountPath: /keys
          name: secret-unsealer-keys
        - mountPath: /var/jenkins_home
          name: jenkins-home
        - mountPath: /var/jenkins_config
          name: jenkins-config
        - mountPath: /usr/share/jenkins/ref/plugins
          name: plugins
        - mountPath: /var/jenkins_plugins
          name: plugin-dir
      containers:
      - name: jenkins
        image: "europe-docker.pkg.dev/dnext-io/ghcr-dnext-technology/dnext-technology/fletcher:v0.12.0"
        imagePullPolicy: "IfNotPresent"
        args: ["--httpPort=8080"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: JAVA_OPTS
          value: >-
            -Dcasc.reload.token=$(POD_NAME) -Dorg.apache.commons.jelly.tags.fmt.timeZone=Asia/Istanbul
            -Dhudson.model.ParametersAction.keepUndefinedParameters=true -Dhudson.model.ParametersAction.safeParameters=SERVICE_NAME,VERSION,SERVICE_SLUG,REPO_NAME,BUILD_GIT_COMMIT,APP_TYPE
            -Dorg.jenkinsci.plugins.workflow.cps.DSL.UNSAFE_GROOVY_INTERPOLATION=ignore
            -Xms1024m -Xmx1024m

        - name: JENKINS_OPTS
          value: >-
            --webroot=/var/jenkins_cache/war 
        - name: JENKINS_SLAVE_AGENT_PORT
          value: "50000"
        - name: HOME
          value: /var/jenkins_home
        - name: JENKINS_CASC_GIT_USERNAME
          valueFrom:
            secretKeyRef:
              key: JENKINS_CASC_GIT_USERNAME
              name: jenkins-casc-secret
        - name: JENKINS_CASC_GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: JENKINS_CASC_GIT_PASSWORD
              name: jenkins-casc-secret
        - name: JENKINS_CASC_VAULT_DEPLOYER_TOKEN_ORBITANT
          valueFrom:
            secretKeyRef:
              key: JENKINS_CASC_VAULT_DEPLOYER_TOKEN_ORBITANT
              name: jenkins-casc-secret
        - name: CASC_JENKINS_CONFIG
          value: /var/jenkins_home/casc_configs
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 50000
          name: agent-listener
        - containerPort: 5000
          name: http-app-server
        - containerPort: 5001
          name: http-ci-utility
        livenessProbe:
          failureThreshold: 100
          httpGet:
            path: '/login'
            port: http
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: '/login'
            port: http
          periodSeconds: 10
          timeoutSeconds: 5
        startupProbe:
          failureThreshold: 100
          httpGet:
            path: '/login'
            port: http
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 2000m
            memory: 2048Mi
          requests:
            cpu: 250m
            memory: 1536Mi
        volumeMounts:
        - mountPath: /tmp/pia/groovy
          name: jenkins-groovy-folder
          readOnly: true
        - mountPath: /tmp/pia/groovy-render
          name: jenkins-groovy-render-folder
        - mountPath: /keys
          name: secret-unsealer-keys
        - mountPath: /var/jenkins_home
          name: jenkins-home
          readOnly: false
        - mountPath: /var/jenkins_config
          name: jenkins-config
          readOnly: true
        - mountPath: /usr/share/jenkins/ref/plugins/
          name: plugin-dir
          readOnly: false
        - name: sc-config-volume
          mountPath: /var/jenkins_home/casc_configs
        - name: admin-secret
          mountPath: /run/secrets/chart-admin-username
          subPath: jenkins-admin-user
          readOnly: true
        - name: admin-secret
          mountPath: /run/secrets/chart-admin-password
          subPath: jenkins-admin-password
          readOnly: true
        - name: jenkins-cache
          mountPath: /var/jenkins_cache
      - name: config-reload
        image: "europe-docker.pkg.dev/dnext-io/ghcr-dnext-technology/dnext-technology/3rd-party/kiwigrid/k8s-sidecar:1.3.0"
        imagePullPolicy: IfNotPresent
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: LABEL
          value: "jenkins-jenkins-config"
        - name: FOLDER
          value: "/var/jenkins_home/casc_configs"
        - name: NAMESPACE
          value: 'hornet'
        - name: REQ_URL
          value: "http://localhost:8080/reload-configuration-as-code/?casc-reload-token=$(POD_NAME)"
        - name: REQ_METHOD
          value: "POST"
        - name: REQ_RETRY_CONNECT
          value: "10"
        - name: REQ_TIMEOUT
          value: "600"
        - name: METHOD
          value: SLEEP
        - name: SLEEP_TIME
          value: "2592000"
        resources: {}
        volumeMounts:
        - name: sc-config-volume
          mountPath: "/var/jenkins_home/casc_configs"
        - name: jenkins-home
          mountPath: /var/jenkins_home
      - command:
        - python3
        - -m
        - flask
        - run
        - --host=0.0.0.0
        - --port=5001
        env:
        - name: PYTHONUNBUFFERED
          value: "TRUE"
        - name: FLASK_APP
          value: registry-only/app_proxy.py
        - name: CONTAINER_REGISTRY_TYPE
          value: docker
        - name: CONTAINER_REGISTRY_USERNAME
          valueFrom:
            secretKeyRef:
              key: registry-username
              name: ci-utility
              optional: false
        - name: CONTAINER_REGISTRY_PASSWORD
          valueFrom:
            secretKeyRef:
              key: registry-password
              name: ci-utility
              optional: false
        - name: CONTAINER_REGISTRY_URL
          valueFrom:
            secretKeyRef:
              key: registry-url
              name: ci-utility
              optional: false
        - name: CONTAINER_REGISTRY_PREFIX
          valueFrom:
            secretKeyRef:
              key: registry-prefix
              name: ci-utility
              optional: false
        - name: IMAGES_LIST
          value: 
            orbitant/order-generation/order-generation,orbitant/product-ordering/product-ordering,orbitant/service-catalog/service-catalog,orbitant/service-inventory/service-inventory,orbitant/service-ordering/service-ordering,orbitant/service-ordering-fulfillment/service-ordering-fulfillment,orbitant/service-ordering-fulfillment-orchestration/service-ordering-fulfillment-orchestration,orbitant/account/account,orbitant/partner/partner,orbitant/agreement/agreement,orbitant/party-role/party-role,orbitant/customer/customer,orbitant/party/party,orbitant/resource-ordering-fulfillment/resource-ordering-fulfillment,orbitant/product-ordering-fulfillment/product-ordering-fulfillment,orbitant/trouble-ticket/trouble-ticket,orbitant/resource-ordering/resource-ordering,orbitant/resource-inventory/resource-inventory,orbitant/product-inventory/product-inventory,orbitant/resource-catalog/resource-catalog,orbitant/product-catalog/product-catalog,orbitant/shopping-cart/shopping-cart,orbitant/document/document,orbitant/product-offering-qualification/product-offering-qualification,orbitant/geographic-address/geographic-address,orbitant/payment-method/payment-method,orbitant/payment/payment,orbitant/job-scheduler/job-scheduler,orbitant/customer-journey/customer-journey,orbitant/backoffice/backoffice,orbitant/href-map/href-map,orbitant/party-interaction-management/party-interaction-management,orbitant/configuration-management/configuration-management,orbitant/storage/storage,orbitant/reference-management/reference-management,orbitant/data-history-management/data-history-management,orbitant/activity-history/activity-history,orbitant/price-engine/price-engine,orbitant/quote/quote,orbitant/promotion-management/promotion-management,orbitant/roles-and-permissions/roles-and-permissions,orbitant/sales-management/sales-management,orbitant/resource-ordering-fulfillment-orchestration/resource-ordering-fulfillment-orchestration,orbitant/product-ordering-fulfillment-orchestration/product-ordering-fulfillment-orchestration,orbitant/rule-engine/rule-engine,orbitant/id-generation-management/id-generation-management,orbitant/loyalty-management/loyalty-management,orbitant/communication/communication,orbitant/audit-log-event-management/audit-log-event-management,orbitant/ddhms-collector/ddhms-collector,orbitant/dalems-collector/dalems-collector,orbitant/dbpm-operate-management/dbpm-operate-management,orbitant/dbpm-form-management/dbpm-form-management,orbitant/dbpm-usertask-management/dbpm-usertask-management,orbitant/privacy-management/privacy-management,orbitant/account-ui/account-ui,orbitant/activity-history-ui/activity-history-ui,orbitant/configuration-management-ui/configuration-management-ui,orbitant/customer-ui/customer-ui,orbitant/document-ui/document-ui,orbitant/party-ui/party-ui,orbitant/service-catalog-ui/service-catalog-ui,orbitant/product-catalog-ui/product-catalog-ui,orbitant/resource-catalog-ui/resource-catalog-ui,orbitant/panoramic-order-ui/panoramic-order-ui,orbitant/cpq-ui/cpq-ui,orbitant/dcomms-ui/dcomms-ui
        image: 
          europe-docker.pkg.dev/dnext-io/ghcr-dnext-technology/dnext-technology/ci-utility:main-20241001-171957-518
        name: ci-utility
      - args:
        - --save
        - ""
        image: 
          europe-docker.pkg.dev/dnext-io/ghcr-dnext-technology/dnext-technology/3rd-party/library/redis:7.2.2
        name: redis
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 128Mi
      - env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: IN_HOUSE_APP_PREFIX
          value: pia-team.com
        - name: PYTHONUNBUFFERED
          value: "TRUE"
        - name: COVERAGE_MODE
          value: namespaced
        - name: FLASK_DEBUG
          value: "1"
        image: 
          europe-docker.pkg.dev/dnext-io/ghcr-dnext-technology/dnext-technology/kube-app-server:main-20241007-162601-527
        name: kube-app-server
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: LABEL
          value: jenkins-job-defs-config
        - name: FOLDER
          value: /tmp/pia/groovy-render
        - name: NAMESPACE
          value: hornet
        image: 
          europe-docker.pkg.dev/dnext-io/ghcr-dnext-technology/dnext-technology/3rd-party/kiwigrid/k8s-sidecar:1.3.0
        imagePullPolicy: IfNotPresent
        name: config-reload-jobs
        volumeMounts:
        - mountPath: /tmp/pia/groovy-render
          name: jenkins-groovy-render-folder

      volumes:
      - configMap:
          name: jenkins-job-defs
        name: jenkins-groovy-folder
      - emptyDir: {}
        name: jenkins-groovy-render-folder
      - emptyDir: {}
        name: secret-unsealer-keys
      - name: plugins
        emptyDir: {}
      - name: jenkins-config
        configMap:
          name: jenkins
      - name: plugin-dir
        emptyDir: {}
      - name: jenkins-cache
        emptyDir: {}
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins
      - name: sc-config-volume
        emptyDir: {}
      - name: admin-secret
        secret:
          secretName: jenkins
      imagePullSecrets:
      - name: reg-creds
