---
# Source: jenkins/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-sealed
  namespace: hornet
  labels:
    "app.kubernetes.io/name": 'jenkins'
    "helm.sh/chart": "jenkins-3.8.8"
    "app.kubernetes.io/managed-by": "Helm"
    "app.kubernetes.io/instance": "jenkins"
    "app.kubernetes.io/component": "jenkins-controller"
    app.kubernetes.io/family: dnext
  annotations:
    pia-team.com/role: pia.k8s.jenkins.customer/0.12.0
    pia-team.com/secret-status: sealed
    pia-team.com/iv: 4cBL7P7ZVNWAiM9z9CeE7g==
    pia-team.com/session-key: 
      rJiLQ7IAySZmZv16PjyVBxPA8CrTgiibpHazGfMnxzQ+1eVPqPuleT+IJklJw1+tDv5tiRxiTOW2L9DagehSBPZ7YJ33cmGCV0KaNnkUmKYIPUBck9rMzfpNluWdJ8ccImhYb4CsLwu5Pc4JDA4Mt4+LWbyAaq14HEPOFqPfGsJtzLk2h74G7eUEMRBgtX43P9S5nFXA+isOURvwr8a9YNWd8eY4vge1AJhkcTIqSFmVp/nCBzWKjHaFZ+WB9dB7PMdq2pDlb4bPQeIJU34Y4VQBLYvwMqLau2pU5F6fRWxbeLs7aKJKJBaAgXFXeWJg23S7DKJkkqTk7Xy+6SBoAw==
type: Opaque
data:
  jenkins-admin-password: "COouvNXQshyTCeeJ0Y8nZUMT4DU="
  jenkins-admin-user: "O90Npcs="
